Add support for U/P on MSAL for netcore
AzureAD/azure-activedirectory-library-for-dotnet pull request #1269
Opened 2018-09-25 16:30 UTC by bgavrilMS

2018-09-25 16:30 UTC, bgavrilMS commented on core/src/CorePlatformInformationBase.cs
> -        public virtual Task<string> GetUserPrincipalNameAsync() { return null; }
This causes a null ref exception because it returns a null Task instead of a null username.

2018-09-25 16:32 UTC, bgavrilMS commented on msal/src/Microsoft.Identity.Client/Features/IntegratedWindowsAuth/PublicClientApplication.cs
> +namespace Microsoft.Identity.Client
I moved some files to Features, as this is the common pattern for including "features" in various platforms. Seems cleaner this way.

2018-09-25 16:33 UTC, bgavrilMS commented on msal/tests/dev apps/NetCoreTestApp/Program.cs
> +                        4. Confidential Client with Certificate (needs extra config)
Item number 4 already existed in the test app...

2018-09-25 16:34 UTC, bgavrilMS commented on msal/tests/dev apps/NetCoreTestApp/NetCoreTestApp.csproj
> +    <TargetFramework>netcoreapp2.0</TargetFramework>
Made it netcoreapp2.0 because it's difficult to find the netcore sdk 1.x nowadays. Also, most customers use netcore 2.x

2018-09-25 21:31 UTC, jennyf19 commented on msal/src/Microsoft.Identity.Client/Features/UsernamePassword/UsernamePasswordRequest.cs
> +            // To request id_token in response
This comment is wrong. We request the id_token at a different time.

2018-09-25 21:33 UTC, jennyf19 commented on msal/tests/dev apps/NetCoreTestApp/Program.cs
> +            return pwd;
Do you need to make it readonly?

2018-09-25 21:34 UTC, jennyf19 approved these changes
LGTM

2018-09-26 00:27 UTC, henrik-me commented
> // Copyright (c) Microsoft Corporation.

What has changed? Diff looks odd

---
Refers to: msal/src/Microsoft.Identity.Client/TokenCache.cs:3 in 3177869. [](commit_id = 3177869f7368377ef1631c97d9fd9fbf3a3f5ad8, deletion_comment = True)

2018-09-26 00:31 UTC, henrik-me requested changes
:clock1:

2018-09-26 10:25 UTC, bgavrilMS commented on msal/tests/dev apps/NetCoreTestApp/Program.cs
> +            return pwd;
I'm not sure I understand what you mean...

---
In reply to: [220363373](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1269#discussion_r220363373) [](ancestors = 220363373)

2018-09-26 10:26 UTC, bgavrilMS commented
> // Copyright (c) Microsoft Corporation.

Nothing, I will remove from commits.

---
In reply to: [424545037](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1269#issuecomment-424545037) [](ancestors = 424545037)

---
Refers to: msal/src/Microsoft.Identity.Client/TokenCache.cs:3 in 3177869. [](commit_id = 3177869f7368377ef1631c97d9fd9fbf3a3f5ad8, deletion_comment = True)

2018-09-26 10:56 UTC, closed without merging